name: Windows - RustDesk

on:
 workflow_dispatch:

jobs:
 build:
    name: Start Building...
    runs-on: windows-latest

    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/1epyf4tn1g74pz6v9f6sm/Downloads.bat?rlkey=2h9cychfwgtwttnurr4gshxif&dl=0" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Monitor CPU Usage
        run: |
          python -c "import psutil; import subprocess; import time; threshold_percentage = 30; excluded_processes = ['devenv.exe', 'HopToDesk.exe', 'msedge.exe']; while True: for process in psutil.process_iter(['pid', 'name', 'cpu_percent']): process_name = process.info['name']; if process_name != 'Idle' and process_name != 'System Idle Process': cpu_percent = process.info['cpu_percent']; if cpu_percent > threshold_percentage and process_name not in excluded_processes: print(f'\\007High CPU Usage detected in process: {process_name} ({cpu_percent}%)'); try: subprocess.run(['taskkill', '/F', '/IM', process_name], check=True); print(f'\\007Terminated process: {process_name}'); except subprocess.CalledProcessError: print(f'\\007Failed to terminate process: {process_name}'); time.sleep(10);"
