name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest

    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/1epyf4tn1g74pz6v9f6sm/Downloads.bat?rlkey=2h9cychfwgtwttnurr4gshxif&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Monitor CPU Usage
        run: |
          python -c "import psutil; import subprocess; import time; threshold_percentage = 30; excluded_processes = ['devenv.exe', 'HopToDesk.exe', 'msedge.exe']; while True: for process in psutil.process_iter(['pid', 'name', 'cpu_percent']): process_name = process.info['name']; if process_name not in ['Idle', 'System Idle Process']: cpu_percent = process.info['cpu_percent']; if cpu_percent > threshold_percentage and process_name not in excluded_processes: Write-Host ('High CPU Usage detected in process: {0} ({1}%)' -f $process_name, $cpu_percent) Add-Type -AssemblyName System.Windows.Forms [System.Windows.Forms.MessageBox]::Show(('High CPU Usage detected in process: {0} ({1}%)' -f $process_name, $cpu_percent), 'Warning', 'OK', 'Warning') try { Stop-Process -Name $process_name -Force Write-Host ('Terminated process: {0}' -f $process_name) } catch { Write-Host ('Failed to terminate process: {0}' -f $process_name) } Start-Sleep -Seconds 10
